steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build' ,'-f' ,'Dockerfile.build', '-t', 'us.gcr.io/el-service/el_service_docker:build' ,'.']
- name: "gcr.io/cloud-builders/docker"
  args: ['create', '--name' ,'mix_docker-437470-tmp' ,'us.gcr.io/el-service/el_service_docker:build']
- name: "gcr.io/cloud-builders/docker"
  args: ['cp', 'mix_docker-437470-tmp:/opt/app/_build/prod/rel/elixir_service/releases/0.0.1/elixir_service.tar.gz' ,'elixir_service.tar.gz']
- name: "gcr.io/cloud-builders/docker"
  args: ['rm' ,'-f', 'mix_docker-437470-tmp']
- name: "gcr.io/cloud-builders/docker"
  args: ['build', '-f', 'Dockerfile.release', '-t', 'us.gcr.io/el-service/el_service_docker:release', '.']
