FROM bitwalker/alpine-erlang:6.1

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ && \
    rm -rf /var/cache/apk/*

EXPOSE 8080
ENV PORT=8080
ENV HOST=$DOCKERCLOUD_SERVICE_FQDN
ENV MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD elixir_service.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/elixir_service"]
